print('Hello World')
print('My Name Is Mr paramat bumrakorn')
print('Nickname: mat')
print('Graduated from Nakhon Phanom Technical College')
print('Nakhon Phanom Province')
print('Currently studying in the 4th year.')
print('Information Technology branch')
print('Faculty of Management Science and Information Technology')
print('Nakhon Phanom University')
print('In the future I want to work as a fisherman.')
