print('Hello World')
print('My Name Is Mr Chayut Songserm')
print('Nickname: Donut')
print('Graduated from Mathayom 6 Nakhon Phanom Witthayakhom School')
print('Nakhon Phanom Province')
print('Currently studying in 3rd year.')
print('Information Technology branch')
print('Faculty of Management and Information Technology')
print('Nakhon Phanom University')
print('In the future I want to work as a programmer.')
