print('Hello World!')
print('Hello World!')
print('Hello World!')
print('Hello World!')
print('Hello World!')
print("trst0")
print("trst0")
print("trst0")
print("trst0")
print("trst0")
print("Gog")
print("Gog")
print("Gog")
print("Gog")
print("Gogodo")